### ISSUE TITLE
能否自定义日志级别或是改进这个warning

### ISSUE THREAD

**Issue by forchannot** [felinae98/nonebot-bison#102]
如图，在nonebot2中运行时warning太多以至于其他插件的信息经常会被刷新到很上面去，能否自定义日志级别或者改进这个warning
![image](https://user-images.githubusercontent.com/100580891/188801212-4d314630-11ea-4cf9-b4fd-d1d5f6a7316c.png)

**Comment by felinae98** [comment]
可以考虑
