### ISSUE TITLE
请问使用docker-compose部署后，如何修改.env文件

### ISSUE THREAD

**Issue by bix-cy** [felinae98/nonebot-bison#103]
使用docker-compose部署，我在docker目录找不到Bot的文件夹

**Comment by felinae98** [comment]
如果使用 docker-compose 部署，请直接在这里https://github.com/felinae98/nonebot-bison/blob/ee88a51868b4ed3d0479b2323a41fe8d8fe05fc9/docker-compose.yml#L12-L19 修改配置项，如果发现有的东西修改后并不起作用，请在这个 issue 下继续反馈

**Comment by bix-cy** [comment]
修改后的文件如下：
environment:
      TZ: Asia/Shanghai
      HOST: 0.0.0.0
      # SUPERUSERS: '[1**]'
      BISON_CONFIG_PATH: /data
      # BISON_OUTER_URL: 'http://192.168.253.131:8080/bison'
      BISON_FILTER_LOG: 'true'
      BISON_USE_PIC: 'false' # 如果需要将文字转为图片发送请改为true
其中192.168.253.131为虚拟机的地址，修改并重启docker后，向BOT发送私聊“后台管理”，bot回复仍是http://localhost:8080/bison/auth/*

**Comment by felinae98** [comment]
yaml 里的 # 是注释的意思，请去掉 # 和后面的空格
