### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by zerobeyondlogic** [felinae98/nonebot-bison#106]
09-20 20:19:04 [ERROR] apscheduler | Job "fetch_and_send (trigger: interval[0:00:10], next run at: 2022-09-20 20:19:14 CST)" raised an exception
Traceback (most recent call last):
  File "/home/beyond/qqbot/bot/bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot_bison/scheduler.py", line 62, in fetch_and_send
    to_send = await platform_manager[target_type].do_fetch_new_post(
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot_bison/platform/platform.py", line 68, in do_fetch_new_post
    return await self.fetch_new_post(target, users)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot_bison/platform/platform.py", line 289, in fetch_new_post
    diff = self.compare_status(target, old_status, new_status)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot_bison/platform/bilibili.py", line 208, in compare_status
    new_status["live_state"] != old_status["live_state"]
TypeError: list indices must be integers or slices, not str

![image](https://user-images.githubusercontent.com/53165745/191255775-cc23755c-8c57-43de-99c4-a2ef2b8a3f2c.png)

**Comment by felinae98** [comment]
排查中

**Comment by AzideCupric** [comment]
可否给一下在用的bison版本

**Comment by zerobeyondlogic** [comment]
nonebot-bison               0.5.4
nonebot2                    2.0.0b5
以下为全部pip依赖

Package                     Version
--------------------------- -----------
aiodns                      3.0.0
aiofiles                    0.8.0
aiohttp                     3.8.1
aiohttp-socks               0.7.1
aiomysql                    0.1.1
aiosignal                   1.2.0
anyio                       3.6.1
APScheduler                 3.9.1
arrow                       1.2.3
asgiref                     3.5.2
async-timeout               4.0.2
attrs                       22.1.0
beautifulsoup4              4.11.1
bidict                      0.22.0
binaryornot                 0.4.4
Brotli                      1.0.9
bs4                         0.0.1
cachetools                  5.2.0
cchardet                    2.1.7
certifi                     2022.9.14
cffi                        1.15.1
chardet                     5.0.0
charset-normalizer          2.1.1
click                       8.1.3
colorama                    0.4.5
cookiecutter                1.7.3
cryptography                38.0.1
cssselect                   1.1.0
diskcache                   5.4.0
expiringdict                1.2.2
fastapi                     0.79.1
feedparser                  6.0.10
frozenlist                  1.3.1
greenlet                    1.1.2
h11                         0.12.0
httpcore                    0.15.0
httptools                   0.5.0
httpx                       0.23.0
httpx-socks                 0.7.4
idna                        3.4
Jinja2                      3.1.2
jinja2-time                 0.2.0
loguru                      0.6.0
lxml                        4.9.1
Markdown                    3.4.1
MarkupSafe                  2.1.1
msgpack                     1.0.4
multidict                   6.0.2
nb-cli                      0.6.7
ndg-httpsclient             0.5.1
nonebot-adapter-cqhttp      2.0.0b1
nonebot-adapter-onebot      2.1.3
nonebot-bison               0.5.4
nonebot-plugin-apscheduler  0.1.2
nonebot-plugin-covid19-news 0.5.6
nonebot-plugin-htmlrender   0.0.4.8
nonebot-plugin-setu4        0.0.18
nonebot-plugin-status       0.4.0
nonebot2                    2.0.0b5
picimagesearch              3.6.1
Pillow                      9.2.0
pip                         22.0.2
playwright                  1.25.2
poyo                        0.5.0
prompt-toolkit              3.0.31
psutil                      5.9.2
pyasn1                      0.4.8
pycares                     4.2.2
pycparser                   2.21
pydantic                    1.9.2
pyee                        8.1.0
pyfiglet                    0.8.post1
Pygments                    2.13.0
pygtrie                     2.5.0
PyJWT                       2.5.0
pymdown-extensions          9.5
PyMySQL                     1.0.2
pyOpenSSL                   22.0.0
pyquery                     1.4.3
PySocks                     1.7.1
python-dateutil             2.8.2
python-dotenv               0.21.0
python-engineio             4.3.4
python-markdown-math        0.8
python-slugify              6.1.2
python-socketio             5.7.1
python-socks                2.0.3
pytz                        2022.2.1
pytz-deprecation-shim       0.1.0.post0
PyYAML                      6.0
requests                    2.28.1
rfc3986                     1.5.0
setuptools                  59.6.0
sgmllib3k                   1.0.0
six                         1.16.0
sniffio                     1.3.0
socksio                     1.0.0
soupsieve                   2.3.2.post1
starlette                   0.19.1
tenacity                    8.0.1
text-unidecode              1.3
tinydb                      4.7.0
tomlkit                     0.10.2
typing_extensions           4.3.0
tzdata                      2022.2
tzlocal                     4.2
urllib3                     1.26.12
uvicorn                     0.18.3
uvloop                      0.17.0
watchfiles                  0.17.0
watchgod                    0.8.2
wcwidth                     0.2.5
websockets                  10.1
yarl                        1.8.1
yetanotherpicsearch         1.6.11

**Comment by zerobeyondlogic** [comment]
好的，谢谢，那我就等更新了。是因为b站的api接口返回的变了么？
