### ISSUE TITLE
在nonebot的.env文件或者.env.prod中更改BISON_OUTER_URL: 配置项无效

### ISSUE THREAD

**Issue by zerobeyondlogic** [felinae98/nonebot-bison#107]
在nonebot的.env文件或者.env.prod中更改BISON_OUTER_URL: 配置项无效，
，到python地址xxx /lib/python3.10/site-packages/nonebot_bison/plugin_config.py文件中更改才生效
![qq_pic_merged_1663677267012](https://user-images.githubusercontent.com/53165745/191258698-ac193756-151d-4a98-a186-57dd4628cdb3.jpg)

**Comment by zerobeyondlogic** [comment]
另外提一个相关的，文档上关于这里表述为：
![image](https://user-images.githubusercontent.com/53165745/191258115-bfd6cd60-d2aa-49ff-b1c5-855162af1aff.png)
但我更改为服务器地址（http://xxxx:8080/bison/"）后仍无法访问（即使是直接更改python中的包中的config文件）
后来才明白，端口也必须和自己的nonebot的端口一致，而不能使用8080，可以在文档中加一句

**Comment by AzideCupric** [comment]
> 另外提一个相关的，文档上关于这里表述为： ![image](https://user-images.githubusercontent.com/53165745/191258115-bfd6cd60-d2aa-49ff-b1c5-855162af1aff.png) 但我更改为服务器地址（[http://xxxx:8080/bison/"）后仍无法访问（即使是直接更改python中的包中的config文件）](http://xxxx:8080/bison/%22%EF%BC%89%E5%90%8E%E4%BB%8D%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%EF%BC%88%E5%8D%B3%E4%BD%BF%E6%98%AF%E7%9B%B4%E6%8E%A5%E6%9B%B4%E6%94%B9python%E4%B8%AD%E7%9A%84%E5%8C%85%E4%B8%AD%E7%9A%84config%E6%96%87%E4%BB%B6%EF%BC%89) 后来才明白，端口也必须和自己的nonebot的端口一致，而不能使用8080，可以在文档中加一句

文档改了了一次但没完全改(
后续会更新的，感谢指正

**Comment by zerobeyondlogic** [comment]
配置文件.env.prod
![image](https://user-images.githubusercontent.com/53165745/191286830-53d490c1-162c-4625-808e-6285ca6edd25.png)
 HOST=0.0.0.0  # 配置 NoneBot2 监听的 IP/主机名
  1 PORT=20010  # 配置 NoneBot2 监听的端口
  2 SUPERUSERS=["2439524442"]  # 配置 NoneBot 超级用户
  3 NICKNAME=["bot","lucy"]  # 配置机器人的昵称
  4 COMMAND_START=["/", ""]  # 配置命令起始字符
  5 COMMAND_SEP=["."]  # 配置命令分割字符
  6
  7 server_status_only_superusers= false
  8
  9 SERVER_STATUS_TEMPLATE="
 10 CPU: {{ '%02d' % cpu_usage }}%
 11 Memory: {{ '%02d' % memory_usage }}%
 12 Disk:
 13 {%- for name, usage in disk_usage.items() %}
 14   {{ name }}: {{ '%02d' % usage.percent }}%
 15 {%- endfor %}
 16 Uptime: {{ uptime }}
 17 "
 18
 19 hikarisearch_max_results=5
 20 BISON_OUTER_URL: str = "http://47.96.90.237:20010/bison/"
 21
 22
 23 #PROXY="socks5://127.0.0.1:10808"
 24 SAUCENAO_API_KEY="c31aa9c95bbada0fa4a788f1cfdd94fa183d8b98"
 25
 26 setu_enable_private = True
 27 setu_withdraw_time = 0
 28 setu_max_num = 20
 29 setu_cd = 10

pyproject.toml文件
![image](https://user-images.githubusercontent.com/53165745/191287444-51007898-2b11-4073-84fa-5187692d8afd.png)
[tool.poetry]
  1 name = "bot"
  2 version = "0.1.0"
  3 description = "bot"
  4 authors = []
  5 readme = "README.md"
  6
  7 [tool.poetry.dependencies]
  8 python = "^3.7.3"
  9 nonebot2 = "^2.0.0-beta.1"
 10
 11 [tool.poetry.dev-dependencies]
 12 nb-cli = "^0.6.0"
 13
 14 [tool.nonebot]
 15 plugins = ["nonebot_plugin_status", "nonebot_bison", "YetAnotherPicSearch", "nonebot_plugin_covid19_news", "nonebot_plugin_setu4"]
 16 plugin_dirs = ["src/plugins"]
 17
 18 [build-system]
 19 requires = ["poetry_core>=1.0.0"]
 20 build-backend = "poetry.core.masonry.api"

**Comment by zerobeyondlogic** [comment]
好的，把.env.prod按您说的改了之后又把plugin_config.py里的改回了原样，远程控制台依旧可用，问题解决，谢谢。
不过bison参考文档里的这部分可以适当更改以避免误解

**Comment by AzideCupric** [comment]
好的多谢建议，其实文档那部分
> - 所有配置项可参考源文件
> - 配置项的配置方法 请参考NoneBot 配置方式，在.env/.env.*文件中写入希望配置的 Bison 配置项

本意是

1. 所有的配置项都写在那个源文件里
2. 如果想在.env里配置相关配置项可以参考NoneBot示例添加

的意思，之后会修改措辞让它更好理解一点
