### ISSUE TITLE
b站直播推送出问题

### ISSUE THREAD

**Issue by bix-cy** [felinae98/nonebot-bison#109]
从9.27之后的直播推送全部没有，删除订阅重新添加之后显示”账号不正确，请重新检查账号”

**Comment by felinae98** [comment]
B站调整了反爬逻辑，正在调查中

**Comment by felinae98** [comment]
暂时解决了这个问题，请更新到最新版

**Comment by bix-cy** [comment]
在源目录中重新执行docker-compose up -d就可以更新了吗

**Comment by felinae98** [comment]
docker-compose pull && docker-compose up -d
