### ISSUE TITLE
放弃对py3.9支持？

### ISSUE THREAD

**Issue by forchannot** [felinae98/nonebot-bison#117]
那python版本应该要多少

**Comment by he0119** [comment]
比 3.9 高一个版本的 3.10...

**Comment by forchannot** [comment]
> 比 3.9 高一个版本的 3.10...

可是我nonebot其他插件都用的3.9.10，得改了（

**Comment by felinae98** [comment]
现在支持的版本为 Python3.10。
如果使用 Windows 请直接安装，如果使用Linux，推荐使用 docker 部署，如果不使用 docker，请自行安装 Python3.10

**Comment by felinae98** [comment]
可以升级到 Python3.10 试试，大部分插件都支持 Python3.10
