### ISSUE TITLE
文档中 nonebot 文档相关链接挂了

### ISSUE THREAD

**Issue by YDX-2147483647** [felinae98/nonebot-bison#123]
https://github.com/felinae98/nonebot-bison/blob/211797f21a1385c401cff989b5dac46653c1a95d/docs/usage/README.md?plain=1#L67

[文档 → 部署 → 部署和使用 → 作为 Bot 使用 → 直接运行（不推荐）](https://nonebot-bison.netlify.app/usage/#%E4%BD%9C%E4%B8%BA-bot-%E4%BD%BF%E7%94%A8)中“[nonebot 的运行方法](https://v2.nonebot.dev/guide/getting-started.html)”挂了。

是否指[**docs**.nonebot.dev 上相应页面](https://docs.nonebot.dev/guide/getting-started.html)？（现在是 **v2**.nonebot.dev）

**Comment by YDX-2147483647** [comment]
文档中还有一些类似的链接，它们都应改成 docs.nonebot.dev 吗？（我发现 [v2.nonebot.dev](https://v2.nonebot.dev) 也确实存在）

https://github.com/felinae98/nonebot-bison/blob/95ca7994cdb4f01495450fdc489e429773f25678/docs/usage/README.md?plain=1#L85

**Comment by AzideCupric** [comment]
> 文档中还有一些类似链接，它们都应改成 docs.nonebot.dev 吗？（我发现 [v2.nonebot.dev](https://v2.nonebot.dev) 也确实存在）
> 
> https://github.com/felinae98/nonebot-bison/blob/95ca7994cdb4f01495450fdc489e429773f25678/docs/usage/README.md?plain=1#L85

之前文档的链接确实是v2.nonebot.dev开头的，应该是最近nonebot的文档迁移过吧(
其实如果发现文档的链接寄了欢迎自己提PR帮助修改的

**Comment by YDX-2147483647** [comment]
好。从 [nonebot.dev](https://nonebot.dev/) 看，docs 是 v1 的文档，似乎是 v2 文档改过结构。
