### ISSUE TITLE
请问下后台管理想要通过nginx反代怎么实现

### ISSUE THREAD

**Issue by forchannot** [felinae98/nonebot-bison#130]
我在通过nginx反代将返回结果设置为了localhost:端口/bison/，在外面输入完整后台管理界面是白屏没有任何东西，应该是最后那一串字符没有传进来，但每次后台管理最后的值都在变，所以想请问下这种情况如何使用nginx反代

**Comment by felinae98** [comment]
没有非常明白你的问题，可以贴一下nginx配置

**Comment by forchannot** [comment]
> 没有非常明白你的问题，可以贴一下nginx配置
我是这么弄的
location /bison/ {
proxy_pass http://localhost:5600/bison/auth/
}

这样设置的话我在外网访问http://ip/bison/xxxxx/(这是每次发后台管理生成的那个)，我想要达到转接到访问http://localhost:5600/bison/auth/xxxxx/，但是这么我这么设置会白屏，所以想请教下应该怎么设置

**Comment by felinae98** [comment]
应该写 `http://localhost:5600/bison/` 就行，不要加上auth

**Comment by forchannot** [comment]
成了，原来auth也是附带的参数嘛，感谢
