### ISSUE TITLE
无法导入插件，报错Cannot load plugin "nonebot_plugin_htmlrender"!

### ISSUE THREAD

**Issue by zhulinyv** [felinae98/nonebot-bison#135]
我在issue中找到了类似的问题[#93](https://github.com/felinae98/nonebot-bison/issues/93#issue-1308964119)，但与其不同的是，我使用的是 poetry 包管理安装的。我无法解决这个问题，希望大佬解答。

![无标题](https://user-images.githubusercontent.com/66541860/199985899-31179701-eb8b-4586-ab44-f9be605052a9.png)
![无标题1](https://user-images.githubusercontent.com/66541860/199985910-4c81859f-c139-437c-b3f1-33a51bc9818b.png)
![无标题2](https://user-images.githubusercontent.com/66541860/199985917-190dacc6-ac4d-43be-88a6-0b5850c68c68.png)
![无标题3](https://user-images.githubusercontent.com/66541860/199985923-750750a6-2bb7-4d8a-801c-8172767cf440.png)
![无标题4](https://user-images.githubusercontent.com/66541860/199985929-cc247240-429d-4363-8250-063b62f180e6.png)

**Comment by felinae98** [comment]
请详细说明下你是怎么「使用 poetry 包管理安装的」，如果操作得当不该存在这个问题

**Comment by zhulinyv** [comment]
> 

poetry run nb plugin install nonebot_bison

**Comment by zhulinyv** [comment]
> 请详细说明下你是怎么「使用 poetry 包管理安装的」，如果操作得当不该存在这个问题

poetry run nb plugin install nonebot_bison

**Comment by felinae98** [comment]
建议再执行一下 poetry install 试试

**Comment by zhulinyv** [comment]
> 建议再执行一下 poetry install 试试

再执行问题以旧，但是我尝试在 bot.py 中提前导入 `nonebot.load_plugin("nonebot_plugin_htmlrender")` 可以解决问题。
谢谢大佬的回复，问题已解决。
