### ISSUE TITLE
提案：支持多种 adaptor

### ISSUE THREAD

**Issue by felinae98** [felinae98/nonebot-bison#137]
## 背景
随着 OneBot V12 的发布，可预期的是未来主流的协议将切换到 OneBot V12。同时，我们（可能）会支持别的协议，如 tg 等。

## 内容
这部分工作内容分为两个部分：接收与发送

### 接收
nonebot2 通过 handler 函数的类型自省来判断该协议的消息会不会通过这个 handler 来处理，我们只需要维护一个新的消息类型，其内容是所有支持的消息类型的 Union

### 发送
需要发送的内容分为两部分，一部分是交互时的回复，另一部分是推送的消息，而且使用不同协议的情况下，需要发送的内容class也不相同。
所以，我们需要自己抽象一些类（例如：文字，图片），我们内部业务逻辑产生文字、图片等抽象类的实例，在发送时，再根据 bot 的 adaptor 的类型将这些抽象类的实例转换为具体协议的 message
可能存在的麻烦：
* 部分类型的消息（例如 QQ音乐 或者 网易云音乐 的分享），在部分平台（QQ）可以用卡片的形式发送，但是在别的平台只能发送 url ，解决的思路是为这些特殊的类型建立特殊的 class，对于可以支持的协议中发送特定的格式的卡片，在别的协议中 fallback 到文本或者 url 。但是这仍然会存在问题，协议不等于聊天软件，qq 适用的 json 消息对于 tg 并不适用，但是如果它们都使用了 onebot 协议，那么其实无法判断其 platform 是什么（这个可能需要 nonebot 的 adaptor 进行支持）
* 可能无法优雅地支持“批量转发”的形式，因为批量转发甚至是和 cqhttp 耦合的

注：这部分内容可以单独抽离出来作为一个新的插件

**Comment by he0119** [comment]
nonebot ob12 adapter 提供的 bot 中已经加上 platform 属性啦。

<https://github.com/nonebot/adapter-onebot/pull/34/commits/d2b1ef4eecc6c43c341e9fc99129cf24105c3bb8>
