### ISSUE TITLE
后台管理删除无效

### ISSUE THREAD

**Issue by forchannot** [felinae98/nonebot-bison#150]
点了删除页面刷新了下还是没删除

**Comment by felinae98** [comment]
有无录屏或者更完善的描述

**Comment by forchannot** [comment]
https://user-images.githubusercontent.com/100580891/203938531-4bce719c-5217-4cfb-968d-6e400b8e513d.mp4

好像是只有rss的删不掉

**Comment by forchannot** [comment]
> 有无录屏或者更完善的描述

我就在这继续发了吧，现在删除可以了，修改还是不行，是没有写修改吗
https://user-images.githubusercontent.com/100580891/205624658-731fba50-cced-4d1e-a028-40b4770054ce.mp4

**Comment by felinae98** [comment]
改订阅地址的话要删掉再重新添加
