### ISSUE TITLE
B站直播开播没提醒

### ISSUE THREAD

**Issue by a0071234c** [felinae98/nonebot-bison#155]
os版本：debian 10
python版本：3.10.8
nonebot2: 2.0.0rc.2
nonebot-bison版本：0.6.2

之前用python的版本是3.9的时候只能用0.5.5的版本，B站直播提醒没有问题。今天把python更新到3.10后，bison也就更新到了最新的0.6.2版本，但是今天发现添加了B站的直播订阅，主播开播的时候没有提醒，go-cqhttp和nb2里面都没有相关的记录。今天刚添加b站直播订阅的时候会报如图的错误，把b站订阅删除后重新添加就不会报了，但重启nb2之后就又会开始报json的错。

![微信图片_20221125213452](https://user-images.githubusercontent.com/35412757/203996794-27ab31fb-5c19-4de0-91cf-d7a0a0ce350e.png)

**Comment by felinae98** [comment]
在最新的main分支中已经修复这个问题，如果着急的话可以自行 clone 项目编译前端后运行
