### ISSUE TITLE
文档网页配置部分有错误

### ISSUE THREAD

**Issue by SCUOP** [felinae98/nonebot-bison#166]
BISON_OUTER_URL: 从外部访问服务器的地址，默认为http://localhost:8080/bison，如果你的插件部署 在服务器上，建议配置为http://<你的服务器ip>:8080/bison 不行
应该改为http://localhost:8080/bison/ 否则会出现http://localhost:8080/bisonauth/#/这种情况

**Comment by AzideCupric** [comment]
bison的官方文档现在是https://nonebot-bison.netlify.app 哦，文档里该部分确实是[http://<你的服务器ip>:8080/bison/](https://nonebot-bison.netlify.app/usage/#%E9%85%8D%E7%BD%AE)，结尾是有`/`没错的
