### ISSUE TITLE
下载不了?

### ISSUE THREAD

**Issue by Annnnh1010** [felinae98/nonebot-bison#172]
![VeryCapture_20230105195501](https://user-images.githubusercontent.com/76246787/210774761-c89115ed-c96c-4d78-a8c2-78e75aaa9433.jpg)

**Comment by AzideCupric** [comment]
![image](https://user-images.githubusercontent.com/57004769/210810296-3918b07d-e9b5-48de-b1db-64cd06a2dd3b.png)
想必不是nonebot-bison的问题

**Comment by Annnnh1010** [comment]
我python是3.8  是太低了么?

**Comment by Annnnh1010** [comment]
o !  谢谢

**Comment by AzideCupric** [comment]
所以提issue的时候建议把环境配置什么的都给一下
这样问题才能解决的快一点(

**Comment by Annnnh1010** [comment]
好的 !
