### ISSUE TITLE
[建议]为后台管理的网页中的订阅帐号加入换行

### ISSUE THREAD

**Issue by yokinanya** [felinae98/nonebot-bison#201]
当订阅帐号为链接的时候，会因为链接较长，超出界面，建议加入换行或截断
如图：
![image](https://user-images.githubusercontent.com/30362789/220036925-72d21495-abfd-42eb-b3a8-2d4e87d294e7.png)

**Comment by felinae98** [comment]
（因为个人时间问题暂时没空更新前端
