### ISSUE TITLE
希望可以将信息合并转发形式推送。消息多的时候容易刷屏。

### ISSUE THREAD

**Issue by JY69** [felinae98/nonebot-bison#202]
例如B站动态消息，图片内容多的时候，容易造成Q群刷屏情况，所以希望可以设置合并转发形式推送

**Comment by AzideCupric** [comment]
也许大抵可能bison其实已经有这个功能了也说不定？

参见官方文档配置项[BISON_USE_PIC_MERGE: 是否启用多图片时合并转发（仅限群）](https://nonebot-bison.netlify.app/usage/#%E9%85%8D%E7%BD%AE)
