### ISSUE TITLE
nonebot2 beta1支持

### ISSUE THREAD

**Issue by kexue-z** [felinae98/nonebot-bison#21]
rt

**Comment by felinae98** [comment]
https://github.com/nonebot/nonebot2/pull/706#issuecomment-1014625739

因为b1的bug，b2发布后会支持beta的版本

**Comment by felinae98** [comment]
dev分支已经基本完成适配，目前因为手头的测试机器人风控了，所以不能确定稳定性，可以先试试

**Comment by felinae98** [comment]
主要功能基本稳定，但是后台还需要继续适配

**Comment by kexue-z** [comment]
发版了嘛？我明天试试！

**Comment by felinae98** [comment]
发版了
