### ISSUE TITLE
同时安装he0119佬的词云插件和本插件时报错

### ISSUE THREAD

**Issue by forchannot** [felinae98/nonebot-bison#216]
File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\nonebot_bison\config\db_config.py", line 8, in <module>
    from sqlmodel import delete, func, select
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\sqlmodel\__init__.py", line 24, in <module>
    from sqlalchemy.schema import ThreadLocalMetaData as ThreadLocalMetaData
ImportError: cannot import name 'ThreadLocalMetaData' from 'sqlalchemy.schema' (C:\Users\Administrator\Desktop\LittlePaimon\.venv\lib\site-packages\sqlalchemy\schema.py)，只截取了最后几行报错日志，前面的应该没太多用，请问下是有什么依赖库版本不对吗，百度了下没有找到合适的答案。he0119佬的词云插件和bison都为最新

**Comment by forchannot** [comment]
好像回不去了，卸载掉词云后还是这样，不知道是拿个库的原因

**Comment by forchannot** [comment]
解决了，更换datastore插件为0.5.6版本没报错，但是这俩插件还是不能装一起

**Comment by felinae98** [comment]
应该是版本不兼容，麻烦贴一下bison版本，datastore版本和wordcloud版本

**Comment by he0119** [comment]
当前只有词云 0.4.4 及之前版本与 bison 0.7.0 兼容。

**Comment by forchannot** [comment]
> 当前只有词云 0.4.4 及之前版本与 bison 0.7.0 兼容。

原来是这样，我直接用nb命令下载的是最新版

**Comment by forchannot** [comment]
> 应该是版本不兼容，麻烦贴一下bison版本，datastore版本和wordcloud版本

似乎datastore不能超过6.0，我用nb安装的词云自动装的6.0以上的版本，回退了就可以了

**Comment by he0119** [comment]
新版本发布了，这下应该不会冲突。直接都更新至最新版本就好。
