### ISSUE TITLE
B站直播推送封面图错误

### ISSUE THREAD

**Issue by forchannot** [felinae98/nonebot-bison#228]
## 环境

- nonebot-bison 版本：0.7.1
- nonebot 版本：
- 安装方式：（以下方式的一种或者其他方式）
  1. 通过 nb-cli 安装
- 操作系统：
win server 2022
## 问题

B站直播封面推送的是上一次直播的某个画面（甚至不是上次的封面），在隔壁harukabot上推送的封面正确
![image](https://user-images.githubusercontent.com/100580891/229113339-1a7b6e76-34b9-4eb6-a66b-cc7e4f0da937.png)
![Screenshot_2023-03-31-19-53-03-008_tv danmaku bil](https://user-images.githubusercontent.com/100580891/229113405-86f1b7d5-6313-4b0f-a903-4a5f738e8168.jpg)

## 日志

```
03-31 19:45:45 [INFO] nonebot_bison | send to User(user=x, user_type='group'): type: Bilibili直播
from: 原神
text: 《原神》3.6版本前瞻特别节目
url: https://live.bilibili.com/21987615
pic: https://i0.hdslb.com/bfs/live-key-frame/keyframe02172130000021987615bki21c.jpg
```

- [√] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [√] 我确认在日志中去掉了敏感信息

**Comment by AzideCupric** [comment]
目前的话bison推送的B站直播所附带的图片是在查询到直播状态变更时，[B站api](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/live/info.md#%E6%89%B9%E9%87%8F%E6%9F%A5%E8%AF%A2%E7%9B%B4%E6%92%AD%E9%97%B4%E7%8A%B6%E6%80%81)所附带的keyframe（也就是直播间某个时间点的截图）:https://github.com/felinae98/nonebot-bison/blob/f16ca6db8bb7c1f908087a77c96d624a2c090489/nonebot_bison/platform/bilibili.py#L298-L302

这么说的话开播提醒应该用主播的直播间封面，而标题变更再用直播间关键帧截图比较好(?

**Comment by SherkeyXD** [comment]
> 这么说的话开播提醒应该用主播的直播间封面，而标题变更再用直播间关键帧截图比较好(?
> 

附议，今天就碰到一次（
