### ISSUE TITLE
我就想设置这两个选项，但是我在  .env.prod    配置后无效，还是发文字和逐一发图，没有合并消息，所以想问下哪里设置

### ISSUE THREAD

**Issue by lintonxue00** [felinae98/nonebot-bison#241]
![image](https://user-images.githubusercontent.com/115356968/233572835-b5841289-5ddb-4179-ad0a-ad9ac265a491.png)
![image](https://user-images.githubusercontent.com/115356968/233573112-c7847c55-63b1-4254-9f9b-f8fcb02883ad.png)
我就想设置这两个选项，但是我在  .env.prod    配置后无效，还是发文字和逐一发图，没有合并消息，所以想问下哪里设置
BISON_USE_PIC: 将文字渲染成图片后进行发送，多用于规避风控
BISON_USE_PIC_MERGE: 是否启用多图片时合并转发（仅限群）
你发的nb配置链接已经失效了，所以我不能参考，
大佬可不可以截个配置图，我参考下就知道了

**Comment by lintonxue00** [comment]
我在plugin_config.py设置好了，但发现BISON_USE_PIC: True这个功能没有用到，我是有安装谷歌浏览器的，但是返回的内容没有图片内容
![image](https://user-images.githubusercontent.com/115356968/233587562-d9ee756d-1aea-4c10-8f7a-f4ad80484782.png)
![image](https://user-images.githubusercontent.com/115356968/233589083-dca07d60-acb1-4e57-af12-a7d94f1e5dd5.png)
![image](https://user-images.githubusercontent.com/115356968/233589383-2cb96d9c-ceb9-4c1f-b60d-2d4a1b1d6443.png)

**Comment by lintonxue00** [comment]
![image](https://user-images.githubusercontent.com/115356968/233593411-fb8261bd-adde-4c00-a137-0941cfbd4e23.png)

**Comment by AzideCupric** [comment]
> ![image](https://user-images.githubusercontent.com/115356968/233592948-ce7e61c8-a3eb-465d-b404-c52886d90d0a.png) 我发现个问题，文本过长可能不会生成图片或者生成图片不稳定，我比较建议作者大大用nonebot-plugin-htmlrender来生成图片

有没有可能bison现在用的就是htmlrender

**Comment by AzideCupric** [comment]
> ![image](https://user-images.githubusercontent.com/115356968/233572835-b5841289-5ddb-4179-ad0a-ad9ac265a491.png) ![image](https://user-images.githubusercontent.com/115356968/233573112-c7847c55-63b1-4254-9f9b-f8fcb02883ad.png) 我就想设置这两个选项，但是我在 .env.prod 配置后无效，还是发文字和逐一发图，没有合并消息，所以想问下哪里设置 BISON_USE_PIC: 将文字渲染成图片后进行发送，多用于规避风控 BISON_USE_PIC_MERGE: 是否启用多图片时合并转发（仅限群） 你发的nb配置链接已经失效了，所以我不能参考， 大佬可不可以截个配置图，我参考下就知道了

配置的名称和值应该使用等号`=`链接而不是冒号`:`
