### ISSUE TITLE
对文档的更新并未同步到文档网站上

### ISSUE THREAD

**Issue by AzideCupric** [felinae98/nonebot-bison#251]
## 环境

- nonebot-bison 版本：-
- nonebot 版本：-
- 安装方式：（以下方式的一种或者其他方式）
  1. 通过 nb-cli 安装
  2. 使用 poetry/pdm 等现代包管理器安装
  3. 通过 pip install 安装
  4. 克隆或下载项目直接使用
- 操作系统：-

## 问题

更新文档后，pr内的预览网站可以正常查看到对文档的相关修改，但是merge之后却未在网站上找到相应的修改

## 举例

#227 在文档中添加了新的配置项
https://github.com/felinae98/nonebot-bison/blob/7956d245cced078dd13a1dc6164f6ef2cf078a21/docs/usage/README.md?plain=1#L151

但在文档中并未出现[https://nonebot-bison.netlify.app/usage/#配置](https://nonebot-bison.netlify.app/usage/#%E9%85%8D%E7%BD%AE)

同样的问题也出现在 #235 上，PR中给出的预览网站是正常的
https://github.com/felinae98/nonebot-bison/pull/235#issuecomment-1501955883

---
- [x] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [x] 我确认在日志中去掉了敏感信息

**Comment by felinae98** [comment]
（开发问题就没必要用那个模板了）

**Comment by AzideCupric** [comment]
> （开发问题就没必要用那个模板了）

那确实是"遇到问题"了啊（
