### ISSUE TITLE
无法访问后台

### ISSUE THREAD

**Issue by NAOLIU** [felinae98/nonebot-bison#264]
## 环境

- nonebot-bison 版本：v0.7.2
- nonebot 版本：b1
- 安装方式：（以下方式的一种或者其他方式）
通过 pip install 安装
- 操作系统：windows11

## 问题

在机器人服务端的本地电脑上无法使用后台管理功能
我无论设置`BISON_OUTER_URL= "http://192.168.2.102:1818/bison/"`还是`BISON_OUTER_URL= "http://127.0.0.1:1818/bison/"`
都无法从机器人返回的链接进入后台管理
没有开网络代理
## 日志
日志无报错

**Comment by felinae98** [comment]
确认监听的是1818端口吗
