### ISSUE TITLE
Nonebot Bison CLI失效

### ISSUE THREAD

**Issue by NAOLIU** [felinae98/nonebot-bison#265]
## 环境

- nonebot-bison 版本：v0.7.2
- nonebot 版本：b1
- 安装方式：
  通过 pip install 安装
- 操作系统：windows11

## 问题

在Nonebot的对应目录输入nb bison export无法导出

## 日志

```
PS F:\BOT\wenwen\NewtBot> nb bison export
Usage: nb [OPTIONS] COMMAND [ARGS]...
Try 'nb --help' for help.

Error: No such command 'bison'.
```

- [√ ] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [ √] 我确认在日志中去掉了敏感信息

**Comment by AzideCupric** [comment]
> - nonebot 版本：b1

nonebot版本多少？
升到正式版看看
