### ISSUE TITLE
Postgresql下：operator does not exist: json = json

### ISSUE THREAD

**Issue by LambdaYH** [felinae98/nonebot-bison#270]
## 环境

- nonebot-bison 版本：https://github.com/felinae98/nonebot-bison/commit/009bfb397eaed2e309dae252cefbf9ead0df4b7a
- nonebot 版本：2.0.0
- 安装方式：（以下方式的一种或者其他方式）
  使用 poetry/pdm 等现代包管理器安装
- 操作系统：Debian11

## 问题

应该是新引入的`user_target`导致的
https://github.com/felinae98/nonebot-bison/blob/009bfb397eaed2e309dae252cefbf9ead0df4b7a/nonebot_bison/config/db_config.py#L88

## 日志

```
"GET /api/subs HTTP/1.0" 500
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class 'asyncpg.exceptions.UndefinedFunctionError'>: operator does not exist: json = json
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

- [x] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [x] 我确认在日志中去掉了敏感信息

**Comment by felinae98** [comment]
用的main上的版本？

**Comment by LambdaYH** [comment]
> 用的main上的版本？

嗯，最新的commit
