### ISSUE TITLE
带图片的转发微博希望能够显示图片

### ISSUE THREAD

**Issue by misaka10078** [felinae98/nonebot-bison#44]
目前获取到的转发消息仅能获得文字内容而无法显示图片，希望能将图片一起通过BOT转发到QQ
![QQ截图20220411224105](https://user-images.githubusercontent.com/40907636/162764321-e4e42a77-5e59-4051-bb85-b478d47dc4c4.png)

**Comment by felinae98** [comment]
可以考虑（不过最近真没空

**Comment by felinae98** [comment]
写了一个初步的版本，可以使用dev分支看看这个功能符合预期吗

**Comment by Yonnemy2nd** [comment]
试了一下图片可以转发了，不过原文的文字视频啥的不行。

**Comment by felinae98** [comment]
文字不行吗，视频本来暂时也不支持

**Comment by Yonnemy2nd** [comment]
之前测试是没有转发原文文字，只有图片。目前没在用dev。
