### ISSUE TITLE
添加订阅后返回404

### ISSUE THREAD

**Issue by zihaozhu93** [felinae98/nonebot-bison#46]
@bot 添加订阅 id，
bot返回消息 ERROR:status code: 404，是姿势不正确吗

**Comment by felinae98** [comment]
提供一下完整截图吧

**Comment by zihaozhu93** [comment]
> 

![image](https://user-images.githubusercontent.com/20263795/163548097-516beb33-a2f8-4529-96f0-6d9ebd6494ad.png)

**Comment by felinae98** [comment]
这应该不是本bot所发生的行为，请排查安装的其他插件
另，只需要@bot 添加订阅 就行，其他参数请在和bot交互的过程中输入
