### ISSUE TITLE
配置失败

### ISSUE THREAD

**Issue by AquamarineCyan** [felinae98/nonebot-bison#53]
- python 3.9.7
- nonebot2_beta1

`.env` 配置
`bison_use_pic: bool = True`
`查询订阅`指令返回仍是文字消息

`plugin_config.py`配置
`bison_use_pic: bool = True`
`查询订阅`指令返回为图片

**Comment by felinae98** [comment]
.env文件的格式请参考https://v2.nonebot.dev/docs/tutorial/configuration

**Comment by AquamarineCyan** [comment]
可以了，`.env`不能声明类型🤣
