### ISSUE TITLE
希望支持设置代理

### ISSUE THREAD

**Issue by MeetWq** [felinae98/nonebot-bison#62]
希望能添加代理的选项，因为给整个机器人全局代理往往会出别的问题

更进一步，或许可以设置某个订阅是否使用代理

**Comment by MeetWq** [comment]
我想通过rsshub订阅tg频道，需要代理才行
至于“别的问题”，我之前试过开全局代理，结果无头浏览器截图会出错
我想说的是让整个机器人走代理不是很好，那样还需要代理软件那边来分流

**Comment by felinae98** [comment]
全局代理是使用的Windows系统设置里的全局代理吗，还是用的HTTP_PROXY和HTTPS_PROXY的环境变量

**Comment by MeetWq** [comment]
设HTTP_PROXY和HTTPS_PROXY

**Comment by felinae98** [comment]
浏览器那边报的错是啥

**Comment by MeetWq** [comment]
并不是这个插件的报错，这不是重点😂
