### ISSUE TITLE
可能会出现操控命令与其他插件冲突的问题

### ISSUE THREAD

**Issue by felinae98** [felinae98/nonebot-bison#64]
> 所以这个之前有什么问题呢

因为 on_command 默认是 block=False , 这样别的插件会接着处理命令，可能会触发别的插件的命令
比如这样
![Snipaste_2022-05-18_16-44-40.png](https://s2.loli.net/2022/05/18/9s6HkmG7b8ZULcX.png)

_Originally posted by @MeetWq in https://github.com/felinae98/nonebot-bison/issues/63#issuecomment-1129739747_

**Comment by MeetWq** [comment]
也不算是冲突，这是我的AI回复插件，@机器人会回复，设的比较低的优先级

**Comment by MeetWq** [comment]
设置 `block=True` 的话可以阻止事件向更低优先级传递
