### ISSUE TITLE
请问可以单独不订阅某个人的某些话题吗

### ISSUE THREAD

**Issue by forchannot** [felinae98/nonebot-bison#67]
比如不订阅A的xxx，xxx话题，但是除这几个外的话题依然订阅

**Comment by felinae98** [comment]
逻辑上打算在设置中加入一个反选tag
* 如果正选反选都不存在 - 不进行过滤（推送全部）
* 如果正选存在反选不存在 - 只推送tag存在在正选列表中的
* 如果正选不存在反选存在- 只推送tag不存在在反选列表中的
* 如果都存在 - 只推送tag存在在正选列表**并且**不存在在反选列表中的
看一下是否合理

**Comment by felinae98** [comment]
如果要做这个需要改配置格式，大概0.6.0才能上（咕咕）

**Comment by forchannot** [comment]
> 逻辑上打算在设置中加入一个反选tag
> 
> * 如果正选反选都不存在 - 不进行过滤（推送全部）
> * 如果正选存在反选不存在 - 只推送tag存在在正选列表中的
> * 如果正选不存在反选存在- 只推送tag不存在在反选列表中的
> * 如果都存在 - 只推送tag存在在正选列表**并且**不存在在反选列表中的
>   看一下是否合理

可以，期待大佬，不过正选反选存在相同tag的情况估计一般人不会去干吧。可以试试添加正选或者反选tag规则时检查已经存在的tag，如果有完全重复的则提示存在重复添加失败。不过我对这方面不是很了解，不知道哪种代码实现起来更为复杂。选择容易实现的方法就行。大佬加油✧٩(ˊωˋ*)و✧

**Comment by forchannot** [comment]
> 如果要做这个需要改配置格式，大概0.6.0才能上（咕咕）

顺便插个题外话，每次更新大概需要多久才会提交到pypi包里面。因为我是通过nb安装的，只能通过pip升级，或者说如果我想从nb安装转变成gitclone到本地直接当插件的话以前的订阅数据能直接移植不

**Comment by felinae98** [comment]
release发布时会自动上传pypi

**Comment by felinae98** [comment]
如果你没有做过额外配置的话，所有配置信息都在data文件夹下，保留这个文件夹即可（当然下个大版本就换地方了）
