### ISSUE TITLE
请求增加图片合并转发.env文件配置

### ISSUE THREAD

**Issue by forchannot** [felinae98/nonebot-bison#79]
在nonebot_bison/plugin_config.py里面把init改为1后更新会覆盖掉变回默认的0，能否把这个图片合并转发设置为.env配置文件中的一部分，这样更新就不会恢复原设置了

**Comment by AquamarineCyan** [comment]
可参考[#53](https://github.com/felinae98/nonebot-bison/issues/53)

**Comment by felinae98** [comment]
所有plugin_config.py里的变量都可以通过.env赋值
请参考https://v2.nonebot.dev/docs/tutorial/configuration
