### ISSUE TITLE
bot无法加载图片

### ISSUE THREAD

**Issue by Argetlaim** [felinae98/nonebot-bison#86]
import nonebot
from pydantic import BaseSettings

这是原代码
class PlugConfig(BaseSettings):

    bison_config_path: str = ""
    bison_use_pic: bool = False
    bison_init_filter: bool = True
    bison_use_queue: bool = True
    bison_outer_url: str = "http://localhost:8080/bison/"
    bison_filter_log: bool = False
    bison_to_me: bool = True
    bison_skip_browser_check: bool = False
    bison_use_pic_merge: int = 1  # 多图片时启用图片合并转发（仅限群）,当bison_use_queue为False时该配置不会生效
    # 0：不启用；1：首条消息单独发送，剩余照片合并转发；2以及以上：所有消息全部合并转发
    bison_resend_times: int = 0

    class Config:
        extra = "ignore"

global_config = nonebot.get_driver().config
plugin_config = PlugConfig(**global_config.dict())

如果用本地那个代码要怎么写？带BISON_BROWSER:吗？写在env里吗
如果用镜像内自带的浏览器，要怎么弄呢？请教下
![image](https://user-images.githubusercontent.com/107046436/172414442-11603745-42eb-4b5e-95e5-9b9875f992d1.png)

**Comment by AzideCupric** [comment]
> 我发上去就变了，不知道什么问题。就还是图片加载不出来，我想问下怎么解决，然后本地那个代码我好像不太会。

1. 图片加载不出来
    图片无法加载出来具体是什么情况，请给出**更加准确的描述**以及**附带nonebot和gocq（如果是的话）的日志或者日志截图**
    在没有相应日志的情况下可能的猜测原因是因为你的bot的QQ账号被风控，导致无法发送图片(仅仅作为猜测，不作为最终结果)
2. 想要对配置项进行配置请参考文档 [配置](https://nonebot-bison-mh8geljlb-azidecupric.vercel.app/usage/#%E9%85%8D%E7%BD%AE)
3. 如果使用docker镜像 请按照 [文档](https://nonebot-bison-mh8geljlb-azidecupric.vercel.app/usage/#docker-compose-%E9%83%A8%E7%BD%B2-%E6%8E%A8%E8%8D%90) 进行操作即可

**Comment by Argetlaim** [comment]
ok的 是这个https://rss.app/feeds/X799MEu0nVpt8dnG.xml

**Comment by felinae98** [comment]
已定位到问题，预计下个版本修复

**Comment by felinae98** [comment]
需要将`entry.media_content`加入pic中
结构如下：
```
In [13]: f.entries[0].media_content
Out[13]: [{'medium': 'image', 'url': 'https://pbs.twimg.com/media/FUqXocOVUAA-3pH.jpg'}]
```

**Comment by Argetlaim** [comment]
看这个url是不是要改很多呀 pic是那个usepic吗
啊总之先谢谢老师了 我就静候下个版本拉

**Comment by Argetlaim** [comment]
更新之后这个是什么意思啊![image](https://user-images.githubusercontent.com/107046436/172854397-c027c8a4-296d-40ca-962f-939cb1727d39.png)

**Comment by AzideCupric** [comment]
显而易见，那一段warning是中文语句
