### ISSUE TITLE
Ubuntu系统无法安装pip包nonebot-bison

### ISSUE THREAD

**Issue by LittlebearHat** [felinae98/nonebot-bison#88]
报错如下：
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.aliyun.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
ERROR: Could not find a version that satisfies the requirement nonebot-bison (from versions: none)
ERROR: No matching distribution found for nonebot-bison

以及手动引入插件出现插件丢失：ModuleNotFoundError: No module named 'socketio'（可能是因为我没有安装这个nonobot-bison的原因？）

**Comment by felinae98** [comment]
不支持python3.8，请安装python3.9及以上版本
