### ISSUE TITLE
使用nb-cli安装nonebot_bison

### ISSUE THREAD

**Issue by MTmin** [felinae98/nonebot-bison#89]
安装完成后使用superuser返回的链接可以登录,但是其中的的群不是返回的全部群,是一部分,其他群管理之类的获取的链接提示登录失败

**Comment by MTmin** [comment]
破案了,不支持多账号

**Comment by felinae98** [comment]
多账号指链接多个QQ吗

**Comment by MTmin** [comment]
> 多账号指链接多个QQ吗

恩呢,我一台服务器登录了好多个QQ,链接了一个n2后端

**Comment by felinae98** [comment]
如果要支持连接多个机器人需要改的东西比较多，而且也有一些设计工作需要完成，短期内不会支持

**Comment by felinae98** [comment]
如果没有别的问题就先close了？
