### ISSUE TITLE
出现了一个我没有订阅过的地址，然后就报错了 虽然不影响使用

### ISSUE THREAD

**Issue by Annnnh1010** [felinae98/nonebot-bison#98]
![_20220812183116](https://user-images.githubusercontent.com/76246787/184337416-b24c98b2-3fa6-4588-b523-25fec4faf6b7.png)

**Comment by felinae98** [comment]
真的没有订阅过微博上的账号吗

**Comment by Annnnh1010** [comment]
> 真的没有订阅过微博上的账号吗

订阅过微博账号 但不是这个ID地址  
还有这种订阅报错
![_20220812195403](https://user-images.githubusercontent.com/76246787/184349234-865f7ead-b3f6-429c-a713-9e9207cd0e35.png)
![2612](https://user-images.githubusercontent.com/76246787/184349318-3e7ea5f9-e13a-4765-8c83-195727cfc672.png)

**Comment by felinae98** [comment]
请求的地址确实和订阅的地址不同，这个是预期的设计
然后请贴一下订阅的 rss 链接排查下一个问题
