### ISSUE TITLE
后台网页空白

### ISSUE THREAD

**Issue by YipSzeho** [felinae98/nonebot-bison#99]
查看元素提示
<noscript>You need to enable JavaScript to run this app.</noscript>
请问如何解决？

**Comment by YipSzeho** [comment]
用的是nb-cli以插件方式部署

**Comment by felinae98** [comment]
可以看看浏览器 console 里的信息，换个浏览器试试

**Comment by YipSzeho** [comment]
用的edge和Firefox都不行0v0
![图片](https://user-images.githubusercontent.com/58989046/187343476-167542b2-1c7e-4fe4-bd80-6081208ba486.png)
![图片](https://user-images.githubusercontent.com/58989046/187343680-260f54fc-cbd3-44b6-853d-dbe53ec73cb7.png)

**Comment by felinae98** [comment]
切到网络的 tab 里看看

**Comment by YipSzeho** [comment]
![图片](https://user-images.githubusercontent.com/58989046/187384313-079923f3-8717-4e27-bbfd-854df9ab5e4b.png)

**Comment by felinae98** [comment]
要不加群问吧

**Comment by YipSzeho** [comment]
解决了，原因是文档没看完（
